
import "./globals.css";

export const metadata = {
  title: "Welcome to demo App",
  description: "Generated by create next app",
};

import TopBar from "@/components/common/Topbar";
import Footer from "@/components/common/Footer";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
         <TopBar />
        {children}

        <Footer/>
      </body>
    </html>
  );
}
